chore: get more data from npm registry
gradejs/gradejs pull request #55
Opened 2022-09-05 18:43 UTC by ctizen

Fixes https://github.com/fingerprintjs/gradejs-backend/issues/179

2022-09-05 18:49 UTC, spalt08 requested changes

2022-09-05 18:49 UTC, spalt08 commented on packages/worker/src/npmRegistry/api.ts
> +      avatar: `https://s.gravatar.com/avatar/${createHash('md5')
I'd extract this into separate function

2022-09-05 18:50 UTC, spalt08 commented
Can you please also update `PackageMetadata` DB model?

2022-09-05 20:22 UTC, spalt08 commented on packages/worker/src/tasks/syncPackageIndexBatch.ts
> +        tags: statsAndMetadata.tags,
nit: I was thinking about keeping the `keywords` naming instead of `tags`. What's your take?

2022-09-06 08:02 UTC, spalt08 commented on packages/worker/src/npmRegistry/api.ts
> +    versionSpecificValues: versionList.reduce((acc, el) => {
nit: what if we make a single `versions: Record<string, VersionData>` property? So the `versionList` can be easily obtained by `Object.keys(versions)`

2022-09-06 08:03 UTC, spalt08 commented on packages/worker/src/npmRegistry/api.ts
> +    versionSpecificValues: versionList.reduce((acc, el) => {
Or `versionMap`

2022-09-06 13:50 UTC, spalt08 approved these changes

2022-09-06 14:26 UTC, zardak approved these changes

2022-09-06 14:40 UTC, merged